### PR TITLE
Release v0.5

### PR DESCRIPTION
**Pull request by jelz**

### CODE REVIEW

**Comment by carlgrundberg** [comment]
Whats the status on this, is it going to be merged soon? Seems like nothing has happened for a couple of months.

**Comment by pauldariye** [comment]
@jelz I'd love to work on closing any remaining issues out for this release.

**Comment by jelz** [comment]
Just to be on the same page: I'm an employee of Contentful and this project is open sourcing of our unofficial GraphQL investigation. Make sure you know about all the [disclaimers](https://github.com/contentful-labs/cf-graphql#disclaimers). I iterate on the project during my regular work hours but the current feature work takes precedence.

That being said, unfortunately I cannot support this release for yet another week, until next Monday. Starting next Monday I'll have 3 weeks of time I can spend on projects like this one. @pauldariye I'll try to go through the issue list tomorrow and will ping you with tasks you could contribute to. Thanks for offering your help :+1:

**Comment by pauldariye** [comment]
Thanks, @jelz .

**Comment by D1no** [comment]
GraphQL is a major requirement for us as its flexibility reselves many regression issues of a growing system. This has driven us to evaluate other headless CMS that are build on top of GraphQL. Needless to say, the staff is used to the UI of contentful so it would be great if this aspect of contentful could get a little more attention from the business side. REST APIs are simply dead in the short run...

Therefore, thank you for devoting your time into this aspect.

**Pull request merged**
